---
title: "Arrange Plots for Use In the Paper"
output: rmarkdown::github_document
author: "Wang Li Rong"
---

# DD Identification

```{r fig.height=12, fig.width=10}
if (!"ggpubr" %in% installed.packages()){
  install.packages("ggpubr")
}
library(ggpubr)

display_doppel = list(
  "DMD"=list(
    "Unbalanced"=doppel_hp_rem,
    "Balanced"=doppel_hp_over_rem
  ),
  "Leukaemia"=list(
    "Unbalanced"=doppel_ag,
    "Balanced"=doppel_ag_over
  ),
  "ALL"=list(
    "Unbalanced"=doppel_ry,
    "Balanced"=doppel_ry_over
  )
)

limits = list(
  "DMD"=c(-0.1, 0.55),
  "Leukaemia"=c(-0.15, 0.75),
  "ALL"=c(-0.05, 0.5)
)

labels = list(
  "DMD"=c('A', 'B'),
  "Leukaemia"=c('C', 'D'),
  "ALL"=c('E', 'F')
)

dataset_subplots = lapply(
  names(display_doppel),
  function(dataset_name){
      row_plot_list = lapply(
      names(display_doppel[[dataset_name]]),
      function(doppel_result_name){
        current_plot = ggpar(
          visualisePPCCDoppelgangers(
            display_doppel[[dataset_name]][[doppel_result_name]]) +
          coord_cartesian(ylim = limits[[dataset_name]]), 
          title=doppel_result_name
        )
        if (dataset_name != "ALL"){
          current_plot = current_plot + rremove("legend")
        }
        if (doppel_result_name == "Balanced"){
          current_plot = current_plot +
            rremove("ylab") +
            rremove("y.ticks")+
            rremove("y.text")
        }
        return(current_plot)
      }
    )
    tmp_subplot = ggarrange(
      plotlist = row_plot_list,
      labels = labels[[dataset_name]],
      align='h',
      ncol = 2, 
      nrow = 1
    ) 
    
    if (dataset_name == "ALL"){
      tmp_subplot = ggarrange(
      plotlist = row_plot_list,
      labels = labels[[dataset_name]],
      align='h',
      common.legend = T,
      legend = "bottom",
      ncol = 2, 
      nrow = 1
    ) 
    }
    
    tmp_subplot = annotate_figure(
      tmp_subplot,
      top = text_grob(
        dataset_name,
        color = "black",
        face = "bold",
        size = 16
      )
    ) 
    return(tmp_subplot)
  }
)
# Arrange both plots
microarray_ddi_plots = ggarrange(
  plotlist = dataset_subplots,
  align='v',
  nrow=3,
  ncol=1
)
# Add big title above
microarray_ddi_plots = annotate_figure(
  microarray_ddi_plots,
  top = text_grob(
    "PPCC DD Identification",
    color = "black",
    face = "bold",
    size = 18
  )
)
microarray_ddi_plots
```

```{r}
# Output
ggsave(filename = file.path(images_dir, "microarray_ddi.tiff"), width = 10, height = 12, device='tiff')
```


## DD Verification

```{r fig.width=8, fig.height=12}
if (!"ggpubr" %in% installed.packages()){
  install.packages("ggpubr")
}
library(ggpubr)
library(glue)

dv_plot_info = list(
  "DMD"=list(
    "veri_result"=veri_results_dmd,
    "ori_names"=c("Doppel_0", "Doppel_2","Doppel_4",
                  "Doppel_6", "Doppel_8", "Doppel_10", 
                  "Pos_Con_10", "Neg_Con"),
    "new_names"=c("0 Doppel", "2 Doppel", "4 Doppel", 
                  "6 Doppel","8 Doppel", "10 Doppel", 
                  "10 Pos Con", "Neg Con"),
    "training_samples"=23,
    "validation_samples"=10
  ),
  "Leukaemia"=list(
    "veri_result"=veri_results_leuk,
    "ori_names"=c("Doppel_0", "Doppel_2", "Doppel_4", 
                  "Doppel_6","Pos_Con_6", "Neg_Con"),
    "new_names"=c("0 Doppel", "2 Doppel", "4 Doppel",
                  "6 Doppel","6 Pos Con", "Neg Con"),
    "training_samples"=48,
    "validation_samples"=10
  ),
  "ALL"=list(
    "veri_result"=veri_results_all,
    "ori_names"=c("Doppel_0", "Doppel_2", "Doppel_4", 
                  "Doppel_5","Pos_Con_5", "Neg_Con"),
    "new_names"=c("0 Doppel", "2 Doppel","4 Doppel", 
                  "5 Doppel","5 Pos Con", "Neg Con"),
    "training_samples"=30,
    "validation_samples"=10
  )
)


dataset_dv_subplots = lapply(
  names(dv_plot_info),
  function(dataset_name){
    veri_results = dv_plot_info[[dataset_name]]$veri_result
    ori_name = dv_plot_info[[dataset_name]]$ori_names
    new_name = dv_plot_info[[dataset_name]]$new_names
    current_plot = visualiseVerificationResults2(
        veri_results, ori_name, new_name
    ) + 
      coord_cartesian(ylim = c(0.3, 1.1)) +
      scale_y_continuous(breaks=seq(0.3,1,0.1)) +
      labs(subtitle=glue("{dv_plot_info[[dataset_name]]$training_samples} Training, {dv_plot_info[[dataset_name]]$validation_samples} Validation")) + 
      theme(plot.subtitle=element_text(size=11, hjust=0.5, color="#2e2e2e")) + 
      theme(plot.title=element_text(size=12, hjust=0.5, color="black", face="bold")) 
    current_plot = ggpar(current_plot, title=dataset_name) 
    return(current_plot)
  }
)

# Arrange both plots
microarray_dv_plots = ggarrange(
  plotlist = dataset_dv_subplots,
  align='v',
  nrow=3,
  ncol=1,
  common.legend = TRUE,
  legend = "bottom",
  labels = c("A", "B", "C")
)

# Add big title above
microarray_dv_plots = annotate_figure(
  microarray_dv_plots,
  top = text_grob("Functional Doppelganger Verification",
  color = "black",
  face = "bold",
  size = 18)
)

microarray_dv_plots

```

```{r}
# Output
ggsave(filename = file.path(images_dir, "microarray_dv.tiff"), width = 8, height = 12, device='tiff')
```


### Additional

```{r fig.width=8, fig.height=12}
if (!"ggpubr" %in% installed.packages()){
  install.packages("ggpubr")
}
library(ggpubr)
library(glue)

dv_add_plot_info = list(
  "DMD"=list(
    "veri_result"=veri_results_dmd_add,
    "ori_names"=c("Doppel_0", "DMD_13_P","NOR_2_P",
                  "NOR_7_P", "Pos_Con_3", "Neg_Con"),
    "new_names"=c("0 Doppel", "DMD_13_P\n(Unbalanced)",
                  "NOR_2_P\n(Unbalanced)","NOR_7_P\n(Unbalanced)", 
                  "3 Pos Con", "Neg Con"),
    "training_samples"=23,
    "validation_samples"=10
  ),
  "Leukaemia"=list(
    "veri_result"=veri_results_leuk_add,
    "ori_names"=c("Doppel_0", "ALL_22_G", "ALL_19_G", 
                  "Pos_Con_2", "Neg_Con"),
    "new_names"=c("0 Doppel", "ALL_22_G\n(Balanced)",
                  "ALL_19_G\n(Balanced)",
                  "2 Pos Con", "Neg Con"),
    "training_samples"=48,
    "validation_samples"=10
  ),
  "ALL"=list(
    "veri_result"=veri_results_all_add,
    "ori_names"=c("Doppel_0", "E2A_2_R", "E2A_13_R", 
                  "Pos_Con_2", "Neg_Con"),
    "new_names"=c("0 Doppel", "E2A_2_R\n(Unbalanced)", 
                  "E2A_13_R\n(Unbalanced)", 
                  "2 Pos Con", "Neg Con"),
    "training_samples"=30,
    "validation_samples"=10
  )
)


dataset_dv_add_subplots = lapply(
  names(dv_add_plot_info),
  function(dataset_name){
    veri_results = dv_add_plot_info[[dataset_name]]$veri_result
    ori_name = dv_add_plot_info[[dataset_name]]$ori_names
    new_name = dv_add_plot_info[[dataset_name]]$new_names
    current_plot = visualiseVerificationResults2(
        veri_results, ori_name, new_name
    ) + 
      coord_cartesian(ylim = c(0.2, 1.05)) +
      scale_y_continuous(breaks=seq(0.3,1,0.1)) +
      labs(subtitle=glue("{dv_add_plot_info[[dataset_name]]$training_samples} Training, {dv_add_plot_info[[dataset_name]]$validation_samples} Validation")) + 
      theme(plot.subtitle=element_text(size=11, hjust=0.5, color="#2e2e2e")) + 
      theme(plot.title=element_text(size=12, hjust=0.5, color="black", face="bold"))
    current_plot = ggpar(current_plot, title=dataset_name) 
    return(current_plot)
  }
)

# Arrange both plots
microarray_dv_add_plots = ggarrange(
  plotlist = dataset_dv_add_subplots,
  align='v',
  nrow=3,
  ncol=1,
  common.legend = TRUE,
  legend = "bottom",
  labels = c("A", "B", "C")
)

# Add big title above
microarray_dv_add_plots = annotate_figure(
  microarray_dv_add_plots,
  top = text_grob("Functional Doppelganger Verification (Additional)",
  color = "black",
  face = "bold",
  size = 18)
)

microarray_dv_add_plots

```
```{r}
# Output
ggsave(filename = file.path(images_dir, "microarray_dv_add.tiff"), width = 8, height = 12, device='tiff')
```

